# Generated by Django 5.2.1 on 2025-06-19 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_userpost_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
